name: news_app
description: Create news app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Cached Network Image [https://pub.dev/packages/cached_network_image]
  cached_network_image: ^3.2.3

  # Cupertino Icons [https://pub.dev/packages/cupertino_icons]
  cupertino_icons: ^1.0.2

  # Equatable [https://pub.dev/packages/equatable]
  equatable: ^2.0.5

  # Floor [https://pub.dev/packages/floor]
  floor: ^1.4.2

  # Flutter Bloc [https://pub.dev/packages/flutter_bloc]
  flutter_bloc: ^8.1.3

  # Flutter Hooks [https://pub.dev/packages/flutter_hooks]
  flutter_hooks: ^0.20.0

  # Get It [https://pub.dev/packages/get_it]
  get_it: ^7.6.0

  # INTL [https://pub.dev/packages/intl]
  intl: ^0.18.1

  # Ionicons [https://pub.dev/packages/ionicons]
  ionicons: ^0.2.2

  # Retrofit [https://pub.dev/packages/retrofit]
  retrofit: ^4.0.1

  # Dartz [https://pub.dev/packages/dartz]
  dartz: ^0.10.1

  # Flutter Dotenv [https://pub.dev/packages/flutter_dotenv]
  flutter_dotenv: ^5.1.0

  # Freezed [https://pub.dev/packages/freezed]
  freezed: ^2.4.1

  # Chopper
  chopper: ^6.1.4



dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  # Build Runner [https://pub.dev/packages/build_runner] 
  build_runner: ^2.3.3

  # Floor Generator [https://pub.dev/packages/floor_generator]
  floor_generator: ^1.4.2

  # Retrofit Generator [https://pub.dev/packages/retrofit_generator]
  retrofit_generator: ^7.0.8

  # Freezed Anotation [https://pub.dev/packages/freezed_annotation]
  freezed_annotation: ^2.4.1

  # Chopper Generator
  chopper_generator: ^6.0.3
flutter:
  uses-material-design: true
  assets:
    - .env

  # Fonts
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
